<style>
   @import url('https://fonts.googleapis.com/css2?family=Belanosima&display=swap');

body {
  font-family: 'Belanosima', sans-serif;
}
    .modal-lg {
        max-width: 80%; 
        height: 700px;
    }
    .action a {
        margin-bottom: 10px;
    }
    .action button{
        margin-bottom: 10px; 


    }
    .action{
        width:200px;
        height: inherit;
        border-radius: 10px;

    }
  .candidatecontainer{
    margin-top:50px;
  }
  .title{
    margin-top:50px;
    text-align:center;
  }
    table td, table th {
        border: 1px solid black;
    }
    .buttonDownload {
 display: inline-block;
 position: relative;
 padding: 10px 25px;
 background-color: #4CC713;
 color: white;
 font-family: sans-serif;
 text-decoration: none;
 font-size: 0.9em;
 text-align: center;
 text-indent: 15px;
 border: none;
}

.buttonDownload:hover {
 background-color: #45a21a;
 color: white;
}

.buttonDownload:before, .buttonDownload:after {
 content: ' ';
 display: block;
 position: absolute;
 left: 15px;
 top: 52%;
}

.buttonDownload:before {
 width: 10px;
 height: 2px;
 border-style: solid;
 border-width: 0 2px 2px;
}

.buttonDownload:after {
 width: 0;
 height: 0;
 margin-left: 3px;
 margin-top: -7px;
 border-style: solid;
 border-width: 4px 4px 0 4px;
 border-color: transparent;
 border-top-color: inherit;
 animation: downloadArrow 1s linear infinite;
 animation-play-state: paused;
}

.buttonDownload:hover:before {
 border-color: #cdefbd;
}

.buttonDownload:hover:after {
 border-top-color: #cdefbd;
 animation-play-state: running;
}

@keyframes downloadArrow {
 0% {
  margin-top: -7px;
  opacity: 1;
 }

 0.001% {
  margin-top: -15px;
  opacity: 0.4;
 }

 50% {
  opacity: 1;
 }

 100% {
  margin-top: 0;
  opacity: 0.4;
 }
}
</style>

<div class="candidatecontainer px-5 py-5">
    <h2 class="title"> <span><i class="bi bi-briefcase"></i></span> Candidate Liste </h2>
    <br><br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Job Name</th>
                <th scope="col">State</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($condidates as $condidate) : ?>
                <tr>
                <tr>
                <td><?= $condidate['id']; ?></td>
                <td><?= $condidate['firstname']; ?></td>
                <td><?= $condidate['lastname']; ?></td>
                <td><?= $condidate['job_name']; ?></td>
                <td><?= $condidate['postulation_state']; ?></td>

                                
                    <td>
                        <div class="action">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal<?= $condidate['id']; ?>">
                        <i class="bi bi-eye"></i>View The details</button><br>
                        <a href="updatestate.php?id=<?= $postulation['id'] ?>" role="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal"><i class="bi bi-pencil">Update the state</i></a>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="updatestate">
                                            <form action="updatestate.php" method="POST">
                                                <div class="form-group">
                                                    <input type="hidden" name="id" value="<?= $condidate['postulation_id']; ?>">
                                                    <label for="state">State</label>
                                                      <select class="form-select" aria-label="Default select example" name="state">
                                                        <br>
                                                        <option selected><?php echo $condidate['postulation_state'];?></option>
                                                        <option value="accepted">accepted</option>
                                                        <option value="refused">refused</option>
                                                        </select>
                                                    </div>
                                                <button type="submit" class="btn btn-primary" name="updatestate" value="updatestate">Update State</button>
                                            </form>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div><br>
                        <a href="emailsend.php?id=<?= $condidate['postulation_id'] ?>&email=<?= $condidate['condidate_email']; ?>&state=<?=$condidate['postulation_state'];?>&namecondidate=<?=$condidate['firstname'].$condidate['lastname'] ;?>&jobname=<?=$condidate['job_name'];?>"role="button" class="btn btn-success"><i class="bi bi-envelope"></i>Send Email</a><br>
                        <a onclick="confirmDelete(<?= $condidate['postulation_id']; ?>)"role="button" class="btn btn-danger"><i class="bi bi-trash"></i>Delete</a>
                        </div>
                    </td>
                  

                </tr>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal<?= $condidate['id']; ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">Candidate Details</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div class="candidatedetails p-4 border rounded">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <h4><strong>Level:</strong><br>
                                             <?php echo $condidate['level']; ?></h4>
                                            <h4><strong>Experience:</strong> <br>
                                            <?php echo $condidate['experience']; ?></h4>
                                            <h4><strong>Telephone Number:</strong> <br> <?php echo $condidate['telephonenumber']; ?></h4>
                                        </div>
                                        <div class="col-md-6">
                                            <h4><strong>CV:</strong></h4>
                                            <button class="buttonDownload" onclick="downloadCV('<?= urlencode($condidate['cv']) ?>')">
                                                Download
                                            </button>
                                        </div>

                                        <script>
                                            function downloadCV(filename) {
                                                window.location.href = 'cvdownload.php?file=' + filename;
                                            }
                                        </script>


                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script src="./assets/sweetalert.js"></script>
<script>
    function confirmDelete(postulationId) {
        Swal.fire({
            title: 'Are you sure?',
            text: 'You won\'t be able to revert this!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = 'deleteapplication.php?id=' + postulationId;
            }
        });
    }


</script>