<style>
@import url('https://fonts.googleapis.com/css2?family=Belanosima&display=swap');

body {
  font-family: 'Belanosima', sans-serif;
}
    .emailForm {
        display: flex;
        width: 100%;
        background-color: #fff;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 800px;
        margin: 50px auto;
    }

    .emailForm .form-content {
        flex: 1;
    }

    .emailForm label {
        display: block;
        margin-bottom: 8px;
    }

    .emailForm input,
    .emailForm textarea {
        width: 100%;
        padding: 10px;
        margin-bottom: 16px;
        box-sizing: border-box;
        border-radius:10px;
        border:1px solid black;
    }

    .emailForm button {
        background-color: #4caf50;
        color: #fff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

    .emailForm button:hover {
        background-color: #45a049;
    }

    .error-message {
        color: #f00;
        margin-bottom: 16px;
    }
</style>

<form class="emailForm" method='POST' action="email.php" onsubmit="return showMessageAlert()">
    <div class="form-content">
        <label for="to"><i class="bi bi-person-circle"></i><span>To:</span></label>
        <input type="email" id="to" name="to" value="<?php echo $email; ?>" required>

        <label for="subject">Subject:</label>
        <input type="text" name="subject" required>

        <label for="message"><i class="bi bi-fonts"></i><span>Message:</span></label>
        <textarea id="message" name="message" rows="20" required></textarea>
        <div class="error-message" id="error-message"></div>

        <button type="submit" value="submit" name="submit" onclick="validateAndSend()"><i class="bi bi-forward-fill"></i><span>Send</span></button>
    </div>
</form>

<script>
    function validateAndSend() {
        var to = document.getElementById('to').value;
        var subject = document.getElementById('subject').value;
        var message = document.getElementById('message').value;

        var errorMessage = '';

        if (!to || !subject || !message) {
            errorMessage = 'Please complete all fields.';
        } else if (!validateEmail(to)) {
            errorMessage = 'Please enter a valid email address.';
        }

        if (errorMessage) {
            document.getElementById('error-message').innerText = errorMessage;
        } else {
            alert('Email sent successfully');
        }
    }

    function validateEmail(email) {
        var re = /\S+@\S+\.\S+/;
        return re.test(email);
    }

    function showMessageAlert() {
       
        Swal.fire({
            icon: 'success',
            title: 'Message sent successfully!',
            showConfirmButton: false,
            timer: 1500  
        });

 
        return true;
    }


</script>
