<style>
    @import url('https://fonts.googleapis.com/css2?family=Belanosima&display=swap');

body {
  font-family: 'Belanosima', sans-serif;
}
    .jobcontainer{
        margin-left:50px;

    }
    .title{
        text-align:center;
        margin-top:50px;
    }
     table td, table th {
        border: 1px solid black;
    }
    tr{
        text-align:center;
        color:#1F618D;
    }
</style>
<div class="jobcontainer ">
    <h2 class="title"> <span><i class="bi bi-briefcase"></i></span> The Job Liste </h2>
    <br>
    <br>
    <br>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Location</th>
                <th scope="col">Creation date</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php if (array_key_exists("msg", $_POST)) : ?>
                <div class="alert alert-success">
                    <?= $_GET['msg']; ?>
                </div>
            <?php endif; ?>
            <?php foreach ($jobs as $job) : ?>
                <tr>
                    <td><?= $job['id']; ?></td>
                    <td><?= $job['name']; ?></td>
                    <td><?= $job['description']; ?></td>
                    <td><?= $job['location']; ?></td>
                    <td><?= $job['createdat']; ?></td>
                    <td>
                        <a href="updatejob.php?id=<?= $job['id'] ?>" role="button" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                        <br>
                        <br>
                        <a href="#" class="btn btn-danger" onclick="confirmDelete(<?= $job['id']; ?>)"><i class="bi bi-trash3-fill"></i></a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script>
    function confirmDelete(jobId) {
        Swal.fire({
            title: 'Are you sure?',
            text: 'You won\'t be able to revert this!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = 'deletejob.php?id=' + jobId;
            }
        });
    }
</script>
