<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.18.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title><?php echo $pagename; ?></title>
    <link rel="stylesheet" href="./assets/home.css" />
    <style>
        a {
            color:black;
        }
    </style>
</head>

<body>
    <header>
        <nav>
            <a class="navbar-brand" href="#"><img src="./assets/ip.png" alt=""></a>
            <div class="mobile-menu">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
            <ul class="nav-list">
                <li><a href="home.php">Home</a></li>
                <li><a href="contactus.php">Contact Us </a></li>
                <li class="login">
                    <a href="loginadmin.php" class="login" style="margin-right:5px"><span><i class="bi bi-person"></i></span>Login</a>
                </li>
            </ul>
        </nav>
    </header>

    <div class="container px-4 py-7">
        <?php include $template . ".phtml"; ?>
    </div>
    <br><br><br><br><br>
    <footer>
        <div class="container text-center" style="margin-top:100px">
            <p>&copy; 2024 InterviewPro. All rights reserved. <span>designed by <span>Monteha Ben Mbarka</span></span></p>
        </div>
    </footer>
    <script src="./assets/home.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>
