<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Kanit:wght@300;500&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="./assets/navbar.css">
    <title><?php echo  $pagename; ?></title>
 
</head>

<body>
    <!--session condition-->
    <?php if (isset($_SESSION['id'])) : ?>
        <nav class="navbar bg-body-tertiary" aria-label="Light offcanvas navbar">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="./assets/ip.png" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarLight" aria-controls="offcanvasNavbarLight" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbarLight" aria-labelledby="offcanvasNavbarLightLabel" >
            <div class="offcanvas-header">
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="dashboard.php">Dashboard</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-briefcase-fill"></i><span style="padding-left:10px">Job</span>
                        </a>
                        <ul  class="dropdown-menu">
                            <li><a class="dropdown-item" href="jobtable.php"> <i class="bi bi-card-list"></i><span style="padding-left:10px">Liste Job</span></a></li>
                            <li><a class="dropdown-item" href="addjob.php"> <i class="bi bi-plus-circle-fill"></i><span style="padding-left:10px">Add Job</span></a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="condidateliste.php"><i class="bi bi-people-fill"></i><span style="padding-left:10px">The applications </span> </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="inbox.php"><i class="bi bi-envelope-at-fill"></i><span style="padding-left:10px">The Inbox</span> </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="logout.php"><i class="bi bi-box-arrow-right"></i><span style="padding-left:10px">Log Out</span> </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

    <?php endif; ?>
    <div class="container px-4 py-7">
        <?php include $template . ".phtml"; ?>
    </div>
    <br><br><br>
    <footer>
      <div class="container text-center " >
        <p style="padding-left:250px;">&copy; 2024 InterviewPro. All rights reserved. <span>designed by <span>Monteha Ben Mbarka</span></span></p>
      </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="./assets/sweetalert.js"></script>
    <?php
    if (isset($_SESSION['status']) && $_SESSION['status'] != "") :
    ?>
        <script>
            Swal.fire({
                title: "<?php echo  $_SESSION['status'];?> ",
                icon: "<?php echo $_SESSION['status_code'];?>"
            });
        </script>
    <?php
        unset($_SESSION['status']);
    endif;
    ?>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">
</body>

</html>
