<style>
    
</style>

<div class="updatestate">
    <form action="" method="POST">
    <div class="form-group">
    <input type="hidden" name="id" value="<?php echo $stateData['id'];?>">
            <label for="date"><i class="bi bi-calendar"></i> State</label>
            <input type="text" name="state" value="<?php echo $stateData['state'];?>">
        </div>
        <button type="submit" class="btn btn-primary" name="updatestate" value="updatestate">Update State</button>
        </form>
</div>